# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'HMOA_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxAppState'
  pod 'ReactorKit'
  pod 'SnapKit'
  pod 'Then'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'TagListView'
  pod 'DropDown'
  pod 'GoogleSignIn'
  pod 'RxKakaoSDKCommon'
  pod 'RxKakaoSDKAuth'
  pod 'RxKakaoSDKUser'
  pod 'RxGesture'

  use_frameworks!

  # Pods for HMOA_iOS

  target 'HMOA_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HMOA_iOSUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
