# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HMOA_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HMOA_iOS

  target 'HMOA_iOSTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SnapKit'
    pod 'Then'
    pod 'Kingfisher'
    pod 'Alamofire'
   
    inherit! :search_paths
    # Pods for testing
  end

  target 'HMOA_iOSUITests' do
    # Pods for testing
  end

end
